package com.unbank.mybatis.mapper;

import com.unbank.mybatis.entity.ArticleKeyword;
import com.unbank.mybatis.entity.ArticleKeywordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleKeywordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_keyword
	 * @mbggenerated  Tue Jan 27 09:49:34 CST 2015
	 */
	int countByExample(ArticleKeywordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_keyword
	 * @mbggenerated  Tue Jan 27 09:49:34 CST 2015
	 */
	int deleteByExample(ArticleKeywordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_keyword
	 * @mbggenerated  Tue Jan 27 09:49:34 CST 2015
	 */
	int deleteByPrimaryKey(Integer keywordid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_keyword
	 * @mbggenerated  Tue Jan 27 09:49:34 CST 2015
	 */
	int insert(ArticleKeyword record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_keyword
	 * @mbggenerated  Tue Jan 27 09:49:34 CST 2015
	 */
	int insertSelective(ArticleKeyword record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_keyword
	 * @mbggenerated  Tue Jan 27 09:49:34 CST 2015
	 */
	List<ArticleKeyword> selectByExample(ArticleKeywordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_keyword
	 * @mbggenerated  Tue Jan 27 09:49:34 CST 2015
	 */
	ArticleKeyword selectByPrimaryKey(Integer keywordid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_keyword
	 * @mbggenerated  Tue Jan 27 09:49:34 CST 2015
	 */
	int updateByExampleSelective(@Param("record") ArticleKeyword record,
			@Param("example") ArticleKeywordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_keyword
	 * @mbggenerated  Tue Jan 27 09:49:34 CST 2015
	 */
	int updateByExample(@Param("record") ArticleKeyword record,
			@Param("example") ArticleKeywordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_keyword
	 * @mbggenerated  Tue Jan 27 09:49:34 CST 2015
	 */
	int updateByPrimaryKeySelective(ArticleKeyword record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_keyword
	 * @mbggenerated  Tue Jan 27 09:49:34 CST 2015
	 */
	int updateByPrimaryKey(ArticleKeyword record);
}