package com.unbank.mybatis.mapper;

import com.unbank.mybatis.entity.ArticleCrawlIdToDocId;
import com.unbank.mybatis.entity.ArticleCrawlIdToDocIdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleCrawlIdToDocIdMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawlid_docid
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	int countByExample(ArticleCrawlIdToDocIdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawlid_docid
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	int deleteByExample(ArticleCrawlIdToDocIdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawlid_docid
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawlid_docid
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	int insert(ArticleCrawlIdToDocId record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawlid_docid
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	int insertSelective(ArticleCrawlIdToDocId record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawlid_docid
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	List<ArticleCrawlIdToDocId> selectByExample(
			ArticleCrawlIdToDocIdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawlid_docid
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	ArticleCrawlIdToDocId selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawlid_docid
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	int updateByExampleSelective(@Param("record") ArticleCrawlIdToDocId record,
			@Param("example") ArticleCrawlIdToDocIdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawlid_docid
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	int updateByExample(@Param("record") ArticleCrawlIdToDocId record,
			@Param("example") ArticleCrawlIdToDocIdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawlid_docid
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	int updateByPrimaryKeySelective(ArticleCrawlIdToDocId record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawlid_docid
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	int updateByPrimaryKey(ArticleCrawlIdToDocId record);
}