package com.unbank.mybatis.mapper;

import com.unbank.mybatis.entity.ArticleCrawlSimilar;
import com.unbank.mybatis.entity.ArticleCrawlSimilarExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleCrawlSimilarMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_similar
	 * @mbggenerated  Thu Apr 30 11:39:45 GMT+08:00 2015
	 */
	int countByExample(ArticleCrawlSimilarExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_similar
	 * @mbggenerated  Thu Apr 30 11:39:45 GMT+08:00 2015
	 */
	int deleteByExample(ArticleCrawlSimilarExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_similar
	 * @mbggenerated  Thu Apr 30 11:39:45 GMT+08:00 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_similar
	 * @mbggenerated  Thu Apr 30 11:39:45 GMT+08:00 2015
	 */
	int insert(ArticleCrawlSimilar record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_similar
	 * @mbggenerated  Thu Apr 30 11:39:45 GMT+08:00 2015
	 */
	int insertSelective(ArticleCrawlSimilar record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_similar
	 * @mbggenerated  Thu Apr 30 11:39:45 GMT+08:00 2015
	 */
	List<ArticleCrawlSimilar> selectByExample(ArticleCrawlSimilarExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_similar
	 * @mbggenerated  Thu Apr 30 11:39:45 GMT+08:00 2015
	 */
	ArticleCrawlSimilar selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_similar
	 * @mbggenerated  Thu Apr 30 11:39:45 GMT+08:00 2015
	 */
	int updateByExampleSelective(@Param("record") ArticleCrawlSimilar record,
			@Param("example") ArticleCrawlSimilarExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_similar
	 * @mbggenerated  Thu Apr 30 11:39:45 GMT+08:00 2015
	 */
	int updateByExample(@Param("record") ArticleCrawlSimilar record,
			@Param("example") ArticleCrawlSimilarExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_similar
	 * @mbggenerated  Thu Apr 30 11:39:45 GMT+08:00 2015
	 */
	int updateByPrimaryKeySelective(ArticleCrawlSimilar record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_similar
	 * @mbggenerated  Thu Apr 30 11:39:45 GMT+08:00 2015
	 */
	int updateByPrimaryKey(ArticleCrawlSimilar record);
}