package com.unbank.mybatis.mapper;

import com.unbank.mybatis.entity.ArticleTextRankKeyword;
import com.unbank.mybatis.entity.ArticleTextRankKeywordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleTextRankKeywordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_textrank_keyword
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	int countByExample(ArticleTextRankKeywordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_textrank_keyword
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	int deleteByExample(ArticleTextRankKeywordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_textrank_keyword
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_textrank_keyword
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	int insert(ArticleTextRankKeyword record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_textrank_keyword
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	int insertSelective(ArticleTextRankKeyword record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_textrank_keyword
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	List<ArticleTextRankKeyword> selectByExample(
			ArticleTextRankKeywordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_textrank_keyword
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	ArticleTextRankKeyword selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_textrank_keyword
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	int updateByExampleSelective(
			@Param("record") ArticleTextRankKeyword record,
			@Param("example") ArticleTextRankKeywordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_textrank_keyword
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	int updateByExample(@Param("record") ArticleTextRankKeyword record,
			@Param("example") ArticleTextRankKeywordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_textrank_keyword
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	int updateByPrimaryKeySelective(ArticleTextRankKeyword record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_textrank_keyword
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	int updateByPrimaryKey(ArticleTextRankKeyword record);
}