package com.unbank.mybatis.mapper;

import com.unbank.mybatis.entity.ArticleCheckKeyword;
import com.unbank.mybatis.entity.ArticleCheckKeywordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleCheckKeywordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_check_keyword
     *
     * @mbggenerated Tue Mar 24 14:49:22 GMT+08:00 2015
     */
    int countByExample(ArticleCheckKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_check_keyword
     *
     * @mbggenerated Tue Mar 24 14:49:22 GMT+08:00 2015
     */
    int deleteByExample(ArticleCheckKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_check_keyword
     *
     * @mbggenerated Tue Mar 24 14:49:22 GMT+08:00 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_check_keyword
     *
     * @mbggenerated Tue Mar 24 14:49:22 GMT+08:00 2015
     */
    int insert(ArticleCheckKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_check_keyword
     *
     * @mbggenerated Tue Mar 24 14:49:22 GMT+08:00 2015
     */
    int insertSelective(ArticleCheckKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_check_keyword
     *
     * @mbggenerated Tue Mar 24 14:49:22 GMT+08:00 2015
     */
    List<ArticleCheckKeyword> selectByExample(ArticleCheckKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_check_keyword
     *
     * @mbggenerated Tue Mar 24 14:49:22 GMT+08:00 2015
     */
    ArticleCheckKeyword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_check_keyword
     *
     * @mbggenerated Tue Mar 24 14:49:22 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") ArticleCheckKeyword record, @Param("example") ArticleCheckKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_check_keyword
     *
     * @mbggenerated Tue Mar 24 14:49:22 GMT+08:00 2015
     */
    int updateByExample(@Param("record") ArticleCheckKeyword record, @Param("example") ArticleCheckKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_check_keyword
     *
     * @mbggenerated Tue Mar 24 14:49:22 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(ArticleCheckKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_check_keyword
     *
     * @mbggenerated Tue Mar 24 14:49:22 GMT+08:00 2015
     */
    int updateByPrimaryKey(ArticleCheckKeyword record);
}