package com.unbank.mybatis.mapper;

import com.unbank.mybatis.entity.ArticlePlateKeyword;
import com.unbank.mybatis.entity.ArticlePlateKeywordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticlePlateKeywordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_plate_keyword
     *
     * @mbggenerated Wed Mar 11 14:17:45 GMT+08:00 2015
     */
    int countByExample(ArticlePlateKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_plate_keyword
     *
     * @mbggenerated Wed Mar 11 14:17:45 GMT+08:00 2015
     */
    int deleteByExample(ArticlePlateKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_plate_keyword
     *
     * @mbggenerated Wed Mar 11 14:17:45 GMT+08:00 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_plate_keyword
     *
     * @mbggenerated Wed Mar 11 14:17:45 GMT+08:00 2015
     */
    int insert(ArticlePlateKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_plate_keyword
     *
     * @mbggenerated Wed Mar 11 14:17:45 GMT+08:00 2015
     */
    int insertSelective(ArticlePlateKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_plate_keyword
     *
     * @mbggenerated Wed Mar 11 14:17:45 GMT+08:00 2015
     */
    List<ArticlePlateKeyword> selectByExample(ArticlePlateKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_plate_keyword
     *
     * @mbggenerated Wed Mar 11 14:17:45 GMT+08:00 2015
     */
    ArticlePlateKeyword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_plate_keyword
     *
     * @mbggenerated Wed Mar 11 14:17:45 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") ArticlePlateKeyword record, @Param("example") ArticlePlateKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_plate_keyword
     *
     * @mbggenerated Wed Mar 11 14:17:45 GMT+08:00 2015
     */
    int updateByExample(@Param("record") ArticlePlateKeyword record, @Param("example") ArticlePlateKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_plate_keyword
     *
     * @mbggenerated Wed Mar 11 14:17:45 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(ArticlePlateKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_plate_keyword
     *
     * @mbggenerated Wed Mar 11 14:17:45 GMT+08:00 2015
     */
    int updateByPrimaryKey(ArticlePlateKeyword record);
}