package com.unbank.mybatis.mapper;

import com.unbank.mybatis.entity.ArticleOrganization;
import com.unbank.mybatis.entity.ArticleOrganizationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleOrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_organization
     *
     * @mbggenerated Sat Feb 28 10:33:05 CST 2015
     */
    int countByExample(ArticleOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_organization
     *
     * @mbggenerated Sat Feb 28 10:33:05 CST 2015
     */
    int deleteByExample(ArticleOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_organization
     *
     * @mbggenerated Sat Feb 28 10:33:05 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_organization
     *
     * @mbggenerated Sat Feb 28 10:33:05 CST 2015
     */
    int insert(ArticleOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_organization
     *
     * @mbggenerated Sat Feb 28 10:33:05 CST 2015
     */
    int insertSelective(ArticleOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_organization
     *
     * @mbggenerated Sat Feb 28 10:33:05 CST 2015
     */
    List<ArticleOrganization> selectByExample(ArticleOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_organization
     *
     * @mbggenerated Sat Feb 28 10:33:05 CST 2015
     */
    ArticleOrganization selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_organization
     *
     * @mbggenerated Sat Feb 28 10:33:05 CST 2015
     */
    int updateByExampleSelective(@Param("record") ArticleOrganization record, @Param("example") ArticleOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_organization
     *
     * @mbggenerated Sat Feb 28 10:33:05 CST 2015
     */
    int updateByExample(@Param("record") ArticleOrganization record, @Param("example") ArticleOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_organization
     *
     * @mbggenerated Sat Feb 28 10:33:05 CST 2015
     */
    int updateByPrimaryKeySelective(ArticleOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_organization
     *
     * @mbggenerated Sat Feb 28 10:33:05 CST 2015
     */
    int updateByPrimaryKey(ArticleOrganization record);
}