package com.unbank.mybatis.mapper;

import com.unbank.mybatis.entity.ArticleUnbankKeyword;
import com.unbank.mybatis.entity.ArticleUnbankKeywordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleUnbankKeywordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_unbank_keyword
     *
     * @mbggenerated Tue Mar 24 14:49:22 GMT+08:00 2015
     */
    int countByExample(ArticleUnbankKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_unbank_keyword
     *
     * @mbggenerated Tue Mar 24 14:49:22 GMT+08:00 2015
     */
    int deleteByExample(ArticleUnbankKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_unbank_keyword
     *
     * @mbggenerated Tue Mar 24 14:49:22 GMT+08:00 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_unbank_keyword
     *
     * @mbggenerated Tue Mar 24 14:49:22 GMT+08:00 2015
     */
    int insert(ArticleUnbankKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_unbank_keyword
     *
     * @mbggenerated Tue Mar 24 14:49:22 GMT+08:00 2015
     */
    int insertSelective(ArticleUnbankKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_unbank_keyword
     *
     * @mbggenerated Tue Mar 24 14:49:22 GMT+08:00 2015
     */
    List<ArticleUnbankKeyword> selectByExample(ArticleUnbankKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_unbank_keyword
     *
     * @mbggenerated Tue Mar 24 14:49:22 GMT+08:00 2015
     */
    ArticleUnbankKeyword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_unbank_keyword
     *
     * @mbggenerated Tue Mar 24 14:49:22 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") ArticleUnbankKeyword record, @Param("example") ArticleUnbankKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_unbank_keyword
     *
     * @mbggenerated Tue Mar 24 14:49:22 GMT+08:00 2015
     */
    int updateByExample(@Param("record") ArticleUnbankKeyword record, @Param("example") ArticleUnbankKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_unbank_keyword
     *
     * @mbggenerated Tue Mar 24 14:49:22 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(ArticleUnbankKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_unbank_keyword
     *
     * @mbggenerated Tue Mar 24 14:49:22 GMT+08:00 2015
     */
    int updateByPrimaryKey(ArticleUnbankKeyword record);
}