package com.unbank.mybatis.mapper;

import com.unbank.mybatis.entity.ArticleLocation;
import com.unbank.mybatis.entity.ArticleLocationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleLocationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_location
     *
     * @mbggenerated Sat Feb 28 10:33:05 CST 2015
     */
    int countByExample(ArticleLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_location
     *
     * @mbggenerated Sat Feb 28 10:33:05 CST 2015
     */
    int deleteByExample(ArticleLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_location
     *
     * @mbggenerated Sat Feb 28 10:33:05 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_location
     *
     * @mbggenerated Sat Feb 28 10:33:05 CST 2015
     */
    int insert(ArticleLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_location
     *
     * @mbggenerated Sat Feb 28 10:33:05 CST 2015
     */
    int insertSelective(ArticleLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_location
     *
     * @mbggenerated Sat Feb 28 10:33:05 CST 2015
     */
    List<ArticleLocation> selectByExample(ArticleLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_location
     *
     * @mbggenerated Sat Feb 28 10:33:05 CST 2015
     */
    ArticleLocation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_location
     *
     * @mbggenerated Sat Feb 28 10:33:05 CST 2015
     */
    int updateByExampleSelective(@Param("record") ArticleLocation record, @Param("example") ArticleLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_location
     *
     * @mbggenerated Sat Feb 28 10:33:05 CST 2015
     */
    int updateByExample(@Param("record") ArticleLocation record, @Param("example") ArticleLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_location
     *
     * @mbggenerated Sat Feb 28 10:33:05 CST 2015
     */
    int updateByPrimaryKeySelective(ArticleLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_location
     *
     * @mbggenerated Sat Feb 28 10:33:05 CST 2015
     */
    int updateByPrimaryKey(ArticleLocation record);
}