package com.unbank.mybatis.mapper;

import com.unbank.mybatis.entity.ClassSection;
import com.unbank.mybatis.entity.ClassSectionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClassSectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_section
     *
     * @mbggenerated Fri Mar 27 10:55:27 GMT+08:00 2015
     */
    int countByExample(ClassSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_section
     *
     * @mbggenerated Fri Mar 27 10:55:27 GMT+08:00 2015
     */
    int deleteByExample(ClassSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_section
     *
     * @mbggenerated Fri Mar 27 10:55:27 GMT+08:00 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_section
     *
     * @mbggenerated Fri Mar 27 10:55:27 GMT+08:00 2015
     */
    int insert(ClassSection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_section
     *
     * @mbggenerated Fri Mar 27 10:55:27 GMT+08:00 2015
     */
    int insertSelective(ClassSection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_section
     *
     * @mbggenerated Fri Mar 27 10:55:27 GMT+08:00 2015
     */
    List<ClassSection> selectByExample(ClassSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_section
     *
     * @mbggenerated Fri Mar 27 10:55:27 GMT+08:00 2015
     */
    ClassSection selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_section
     *
     * @mbggenerated Fri Mar 27 10:55:27 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") ClassSection record, @Param("example") ClassSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_section
     *
     * @mbggenerated Fri Mar 27 10:55:27 GMT+08:00 2015
     */
    int updateByExample(@Param("record") ClassSection record, @Param("example") ClassSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_section
     *
     * @mbggenerated Fri Mar 27 10:55:27 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(ClassSection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_section
     *
     * @mbggenerated Fri Mar 27 10:55:27 GMT+08:00 2015
     */
    int updateByPrimaryKey(ClassSection record);
}