package com.unbank.mybatis.mapper;

import com.unbank.mybatis.entity.ClassTitleKeyword;
import com.unbank.mybatis.entity.ClassTitleKeywordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClassTitleKeywordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_title_keyword
     *
     * @mbggenerated Mon May 25 16:16:39 GMT+08:00 2015
     */
    int countByExample(ClassTitleKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_title_keyword
     *
     * @mbggenerated Mon May 25 16:16:39 GMT+08:00 2015
     */
    int deleteByExample(ClassTitleKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_title_keyword
     *
     * @mbggenerated Mon May 25 16:16:39 GMT+08:00 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_title_keyword
     *
     * @mbggenerated Mon May 25 16:16:39 GMT+08:00 2015
     */
    int insert(ClassTitleKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_title_keyword
     *
     * @mbggenerated Mon May 25 16:16:39 GMT+08:00 2015
     */
    int insertSelective(ClassTitleKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_title_keyword
     *
     * @mbggenerated Mon May 25 16:16:39 GMT+08:00 2015
     */
    List<ClassTitleKeyword> selectByExample(ClassTitleKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_title_keyword
     *
     * @mbggenerated Mon May 25 16:16:39 GMT+08:00 2015
     */
    ClassTitleKeyword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_title_keyword
     *
     * @mbggenerated Mon May 25 16:16:39 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") ClassTitleKeyword record, @Param("example") ClassTitleKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_title_keyword
     *
     * @mbggenerated Mon May 25 16:16:39 GMT+08:00 2015
     */
    int updateByExample(@Param("record") ClassTitleKeyword record, @Param("example") ClassTitleKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_title_keyword
     *
     * @mbggenerated Mon May 25 16:16:39 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(ClassTitleKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_title_keyword
     *
     * @mbggenerated Mon May 25 16:16:39 GMT+08:00 2015
     */
    int updateByPrimaryKey(ClassTitleKeyword record);
}