package com.unbank.mybatis.mapper;

import com.unbank.mybatis.entity.ClassNoNeedKeyword;
import com.unbank.mybatis.entity.ClassNoNeedKeywordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClassNoNeedKeywordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_no_need_keyword
     *
     * @mbggenerated Tue May 19 15:23:55 GMT+08:00 2015
     */
    int countByExample(ClassNoNeedKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_no_need_keyword
     *
     * @mbggenerated Tue May 19 15:23:55 GMT+08:00 2015
     */
    int deleteByExample(ClassNoNeedKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_no_need_keyword
     *
     * @mbggenerated Tue May 19 15:23:55 GMT+08:00 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_no_need_keyword
     *
     * @mbggenerated Tue May 19 15:23:55 GMT+08:00 2015
     */
    int insert(ClassNoNeedKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_no_need_keyword
     *
     * @mbggenerated Tue May 19 15:23:55 GMT+08:00 2015
     */
    int insertSelective(ClassNoNeedKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_no_need_keyword
     *
     * @mbggenerated Tue May 19 15:23:55 GMT+08:00 2015
     */
    List<ClassNoNeedKeyword> selectByExample(ClassNoNeedKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_no_need_keyword
     *
     * @mbggenerated Tue May 19 15:23:55 GMT+08:00 2015
     */
    ClassNoNeedKeyword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_no_need_keyword
     *
     * @mbggenerated Tue May 19 15:23:55 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") ClassNoNeedKeyword record, @Param("example") ClassNoNeedKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_no_need_keyword
     *
     * @mbggenerated Tue May 19 15:23:55 GMT+08:00 2015
     */
    int updateByExample(@Param("record") ClassNoNeedKeyword record, @Param("example") ClassNoNeedKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_no_need_keyword
     *
     * @mbggenerated Tue May 19 15:23:55 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(ClassNoNeedKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_no_need_keyword
     *
     * @mbggenerated Tue May 19 15:23:55 GMT+08:00 2015
     */
    int updateByPrimaryKey(ClassNoNeedKeyword record);
}