package com.unbank.mybatis.mapper;

import com.unbank.mybatis.entity.CustModuleConstraint;
import com.unbank.mybatis.entity.CustModuleConstraintExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustModuleConstraintMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moduleconstraint
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    int countByExample(CustModuleConstraintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moduleconstraint
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    int deleteByExample(CustModuleConstraintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moduleconstraint
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moduleconstraint
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    int insert(CustModuleConstraint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moduleconstraint
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    int insertSelective(CustModuleConstraint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moduleconstraint
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    List<CustModuleConstraint> selectByExampleWithBLOBs(CustModuleConstraintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moduleconstraint
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    List<CustModuleConstraint> selectByExample(CustModuleConstraintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moduleconstraint
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    CustModuleConstraint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moduleconstraint
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") CustModuleConstraint record, @Param("example") CustModuleConstraintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moduleconstraint
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    int updateByExampleWithBLOBs(@Param("record") CustModuleConstraint record, @Param("example") CustModuleConstraintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moduleconstraint
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    int updateByExample(@Param("record") CustModuleConstraint record, @Param("example") CustModuleConstraintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moduleconstraint
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(CustModuleConstraint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moduleconstraint
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    int updateByPrimaryKeyWithBLOBs(CustModuleConstraint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moduleconstraint
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    int updateByPrimaryKey(CustModuleConstraint record);
}