package com.unbank.mybatis.mapper;

import com.unbank.mybatis.entity.CustModule;
import com.unbank.mybatis.entity.CustModuleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    int countByExample(CustModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    int deleteByExample(CustModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    int deleteByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    int insert(CustModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    int insertSelective(CustModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    List<CustModule> selectByExample(CustModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    CustModule selectByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") CustModule record, @Param("example") CustModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    int updateByExample(@Param("record") CustModule record, @Param("example") CustModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(CustModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    int updateByPrimaryKey(CustModule record);
}