package com.unbank.mybatis.mapper;

import com.unbank.mybatis.entity.CustUser;
import com.unbank.mybatis.entity.CustUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    int countByExample(CustUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    int deleteByExample(CustUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    int insert(CustUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    int insertSelective(CustUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    List<CustUser> selectByExample(CustUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    CustUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") CustUser record, @Param("example") CustUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    int updateByExample(@Param("record") CustUser record, @Param("example") CustUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(CustUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    int updateByPrimaryKey(CustUser record);
}