package com.unbank.mybatis.mapper;

import com.unbank.mybatis.entity.UserErrorPushInfo;
import com.unbank.mybatis.entity.UserErrorPushInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserErrorPushInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_error_push_info
     *
     * @mbggenerated Fri Jun 19 10:15:51 GMT+08:00 2015
     */
    int countByExample(UserErrorPushInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_error_push_info
     *
     * @mbggenerated Fri Jun 19 10:15:51 GMT+08:00 2015
     */
    int deleteByExample(UserErrorPushInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_error_push_info
     *
     * @mbggenerated Fri Jun 19 10:15:51 GMT+08:00 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_error_push_info
     *
     * @mbggenerated Fri Jun 19 10:15:51 GMT+08:00 2015
     */
    int insert(UserErrorPushInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_error_push_info
     *
     * @mbggenerated Fri Jun 19 10:15:51 GMT+08:00 2015
     */
    int insertSelective(UserErrorPushInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_error_push_info
     *
     * @mbggenerated Fri Jun 19 10:15:51 GMT+08:00 2015
     */
    List<UserErrorPushInfo> selectByExampleWithBLOBs(UserErrorPushInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_error_push_info
     *
     * @mbggenerated Fri Jun 19 10:15:51 GMT+08:00 2015
     */
    List<UserErrorPushInfo> selectByExample(UserErrorPushInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_error_push_info
     *
     * @mbggenerated Fri Jun 19 10:15:51 GMT+08:00 2015
     */
    UserErrorPushInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_error_push_info
     *
     * @mbggenerated Fri Jun 19 10:15:51 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") UserErrorPushInfo record, @Param("example") UserErrorPushInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_error_push_info
     *
     * @mbggenerated Fri Jun 19 10:15:51 GMT+08:00 2015
     */
    int updateByExampleWithBLOBs(@Param("record") UserErrorPushInfo record, @Param("example") UserErrorPushInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_error_push_info
     *
     * @mbggenerated Fri Jun 19 10:15:51 GMT+08:00 2015
     */
    int updateByExample(@Param("record") UserErrorPushInfo record, @Param("example") UserErrorPushInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_error_push_info
     *
     * @mbggenerated Fri Jun 19 10:15:51 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(UserErrorPushInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_error_push_info
     *
     * @mbggenerated Fri Jun 19 10:15:51 GMT+08:00 2015
     */
    int updateByPrimaryKeyWithBLOBs(UserErrorPushInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_error_push_info
     *
     * @mbggenerated Fri Jun 19 10:15:51 GMT+08:00 2015
     */
    int updateByPrimaryKey(UserErrorPushInfo record);
}