package com.unbank.mybatis.mapper;

import com.unbank.mybatis.entity.WebSiteInfo;
import com.unbank.mybatis.entity.WebSiteInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WebSiteInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website
     *
     * @mbggenerated Mon Dec 08 09:51:29 CST 2014
     */
    int countByExample(WebSiteInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website
     *
     * @mbggenerated Mon Dec 08 09:51:29 CST 2014
     */
    int deleteByExample(WebSiteInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website
     *
     * @mbggenerated Mon Dec 08 09:51:29 CST 2014
     */
    int deleteByPrimaryKey(Integer websiteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website
     *
     * @mbggenerated Mon Dec 08 09:51:29 CST 2014
     */
    int insert(WebSiteInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website
     *
     * @mbggenerated Mon Dec 08 09:51:29 CST 2014
     */
    int insertSelective(WebSiteInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website
     *
     * @mbggenerated Mon Dec 08 09:51:29 CST 2014
     */
    List<WebSiteInfo> selectByExample(WebSiteInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website
     *
     * @mbggenerated Mon Dec 08 09:51:29 CST 2014
     */
    WebSiteInfo selectByPrimaryKey(Integer websiteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website
     *
     * @mbggenerated Mon Dec 08 09:51:29 CST 2014
     */
    int updateByExampleSelective(@Param("record") WebSiteInfo record, @Param("example") WebSiteInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website
     *
     * @mbggenerated Mon Dec 08 09:51:29 CST 2014
     */
    int updateByExample(@Param("record") WebSiteInfo record, @Param("example") WebSiteInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website
     *
     * @mbggenerated Mon Dec 08 09:51:29 CST 2014
     */
    int updateByPrimaryKeySelective(WebSiteInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website
     *
     * @mbggenerated Mon Dec 08 09:51:29 CST 2014
     */
    int updateByPrimaryKey(WebSiteInfo record);
}