package com.unbank.mybatis.entity;

import java.util.Date;

public class ArticleCrawlSimilar {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_crawl_similar.id
	 * @mbggenerated  Thu Apr 30 11:39:45 GMT+08:00 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_crawl_similar.crawl_id
	 * @mbggenerated  Thu Apr 30 11:39:45 GMT+08:00 2015
	 */
	private Integer crawlId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_crawl_similar.similar_id
	 * @mbggenerated  Thu Apr 30 11:39:45 GMT+08:00 2015
	 */
	private Integer similarId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_crawl_similar.webiste_id
	 * @mbggenerated  Thu Apr 30 11:39:45 GMT+08:00 2015
	 */
	private Integer webisteId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_crawl_similar.web_name
	 * @mbggenerated  Thu Apr 30 11:39:45 GMT+08:00 2015
	 */
	private String webName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_crawl_similar.classname
	 * @mbggenerated  Thu Apr 30 11:39:45 GMT+08:00 2015
	 */
	private String classname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_crawl_similar.hotnum
	 * @mbggenerated  Thu Apr 30 11:39:45 GMT+08:00 2015
	 */
	private Integer hotnum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_crawl_similar.istask
	 * @mbggenerated  Thu Apr 30 11:39:45 GMT+08:00 2015
	 */
	private Integer istask;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_crawl_similar.crawl_time
	 * @mbggenerated  Thu Apr 30 11:39:45 GMT+08:00 2015
	 */
	private Date crawlTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_crawl_similar.news_time
	 * @mbggenerated  Thu Apr 30 11:39:45 GMT+08:00 2015
	 */
	private Date newsTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_crawl_similar.id
	 * @return  the value of ptf_crawl_similar.id
	 * @mbggenerated  Thu Apr 30 11:39:45 GMT+08:00 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_crawl_similar.id
	 * @param id  the value for ptf_crawl_similar.id
	 * @mbggenerated  Thu Apr 30 11:39:45 GMT+08:00 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_crawl_similar.crawl_id
	 * @return  the value of ptf_crawl_similar.crawl_id
	 * @mbggenerated  Thu Apr 30 11:39:45 GMT+08:00 2015
	 */
	public Integer getCrawlId() {
		return crawlId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_crawl_similar.crawl_id
	 * @param crawlId  the value for ptf_crawl_similar.crawl_id
	 * @mbggenerated  Thu Apr 30 11:39:45 GMT+08:00 2015
	 */
	public void setCrawlId(Integer crawlId) {
		this.crawlId = crawlId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_crawl_similar.similar_id
	 * @return  the value of ptf_crawl_similar.similar_id
	 * @mbggenerated  Thu Apr 30 11:39:45 GMT+08:00 2015
	 */
	public Integer getSimilarId() {
		return similarId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_crawl_similar.similar_id
	 * @param similarId  the value for ptf_crawl_similar.similar_id
	 * @mbggenerated  Thu Apr 30 11:39:45 GMT+08:00 2015
	 */
	public void setSimilarId(Integer similarId) {
		this.similarId = similarId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_crawl_similar.webiste_id
	 * @return  the value of ptf_crawl_similar.webiste_id
	 * @mbggenerated  Thu Apr 30 11:39:45 GMT+08:00 2015
	 */
	public Integer getWebisteId() {
		return webisteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_crawl_similar.webiste_id
	 * @param webisteId  the value for ptf_crawl_similar.webiste_id
	 * @mbggenerated  Thu Apr 30 11:39:45 GMT+08:00 2015
	 */
	public void setWebisteId(Integer webisteId) {
		this.webisteId = webisteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_crawl_similar.web_name
	 * @return  the value of ptf_crawl_similar.web_name
	 * @mbggenerated  Thu Apr 30 11:39:45 GMT+08:00 2015
	 */
	public String getWebName() {
		return webName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_crawl_similar.web_name
	 * @param webName  the value for ptf_crawl_similar.web_name
	 * @mbggenerated  Thu Apr 30 11:39:45 GMT+08:00 2015
	 */
	public void setWebName(String webName) {
		this.webName = webName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_crawl_similar.classname
	 * @return  the value of ptf_crawl_similar.classname
	 * @mbggenerated  Thu Apr 30 11:39:45 GMT+08:00 2015
	 */
	public String getClassname() {
		return classname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_crawl_similar.classname
	 * @param classname  the value for ptf_crawl_similar.classname
	 * @mbggenerated  Thu Apr 30 11:39:45 GMT+08:00 2015
	 */
	public void setClassname(String classname) {
		this.classname = classname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_crawl_similar.hotnum
	 * @return  the value of ptf_crawl_similar.hotnum
	 * @mbggenerated  Thu Apr 30 11:39:45 GMT+08:00 2015
	 */
	public Integer getHotnum() {
		return hotnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_crawl_similar.hotnum
	 * @param hotnum  the value for ptf_crawl_similar.hotnum
	 * @mbggenerated  Thu Apr 30 11:39:45 GMT+08:00 2015
	 */
	public void setHotnum(Integer hotnum) {
		this.hotnum = hotnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_crawl_similar.istask
	 * @return  the value of ptf_crawl_similar.istask
	 * @mbggenerated  Thu Apr 30 11:39:45 GMT+08:00 2015
	 */
	public Integer getIstask() {
		return istask;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_crawl_similar.istask
	 * @param istask  the value for ptf_crawl_similar.istask
	 * @mbggenerated  Thu Apr 30 11:39:45 GMT+08:00 2015
	 */
	public void setIstask(Integer istask) {
		this.istask = istask;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_crawl_similar.crawl_time
	 * @return  the value of ptf_crawl_similar.crawl_time
	 * @mbggenerated  Thu Apr 30 11:39:45 GMT+08:00 2015
	 */
	public Date getCrawlTime() {
		return crawlTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_crawl_similar.crawl_time
	 * @param crawlTime  the value for ptf_crawl_similar.crawl_time
	 * @mbggenerated  Thu Apr 30 11:39:45 GMT+08:00 2015
	 */
	public void setCrawlTime(Date crawlTime) {
		this.crawlTime = crawlTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_crawl_similar.news_time
	 * @return  the value of ptf_crawl_similar.news_time
	 * @mbggenerated  Thu Apr 30 11:39:45 GMT+08:00 2015
	 */
	public Date getNewsTime() {
		return newsTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_crawl_similar.news_time
	 * @param newsTime  the value for ptf_crawl_similar.news_time
	 * @mbggenerated  Thu Apr 30 11:39:45 GMT+08:00 2015
	 */
	public void setNewsTime(Date newsTime) {
		this.newsTime = newsTime;
	}
}