package com.unbank.mybatis.entity;

public class ArticleTextRankKeyword {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_crawl_textrank_keyword.id
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_crawl_textrank_keyword.crawl_id
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	private Integer crawlId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_crawl_textrank_keyword.keyword
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	private String keyword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_crawl_textrank_keyword.score
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	private Float score;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_crawl_textrank_keyword.id
	 * @return  the value of ptf_crawl_textrank_keyword.id
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_crawl_textrank_keyword.id
	 * @param id  the value for ptf_crawl_textrank_keyword.id
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_crawl_textrank_keyword.crawl_id
	 * @return  the value of ptf_crawl_textrank_keyword.crawl_id
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	public Integer getCrawlId() {
		return crawlId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_crawl_textrank_keyword.crawl_id
	 * @param crawlId  the value for ptf_crawl_textrank_keyword.crawl_id
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	public void setCrawlId(Integer crawlId) {
		this.crawlId = crawlId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_crawl_textrank_keyword.keyword
	 * @return  the value of ptf_crawl_textrank_keyword.keyword
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	public String getKeyword() {
		return keyword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_crawl_textrank_keyword.keyword
	 * @param keyword  the value for ptf_crawl_textrank_keyword.keyword
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_crawl_textrank_keyword.score
	 * @return  the value of ptf_crawl_textrank_keyword.score
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	public Float getScore() {
		return score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_crawl_textrank_keyword.score
	 * @param score  the value for ptf_crawl_textrank_keyword.score
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	public void setScore(Float score) {
		this.score = score;
	}
}