package com.unbank.mybatis.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ArticleKeywordExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ptf_crawl_keyword
	 * @mbggenerated  Tue Jan 27 09:49:34 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ptf_crawl_keyword
	 * @mbggenerated  Tue Jan 27 09:49:34 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ptf_crawl_keyword
	 * @mbggenerated  Tue Jan 27 09:49:34 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_keyword
	 * @mbggenerated  Tue Jan 27 09:49:34 CST 2015
	 */
	public ArticleKeywordExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_keyword
	 * @mbggenerated  Tue Jan 27 09:49:34 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_keyword
	 * @mbggenerated  Tue Jan 27 09:49:34 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_keyword
	 * @mbggenerated  Tue Jan 27 09:49:34 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_keyword
	 * @mbggenerated  Tue Jan 27 09:49:34 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_keyword
	 * @mbggenerated  Tue Jan 27 09:49:34 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_keyword
	 * @mbggenerated  Tue Jan 27 09:49:34 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_keyword
	 * @mbggenerated  Tue Jan 27 09:49:34 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_keyword
	 * @mbggenerated  Tue Jan 27 09:49:34 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_keyword
	 * @mbggenerated  Tue Jan 27 09:49:34 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_keyword
	 * @mbggenerated  Tue Jan 27 09:49:34 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ptf_crawl_keyword
	 * @mbggenerated  Tue Jan 27 09:49:34 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition,
				List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andKeywordidIsNull() {
			addCriterion("keywordid is null");
			return (Criteria) this;
		}

		public Criteria andKeywordidIsNotNull() {
			addCriterion("keywordid is not null");
			return (Criteria) this;
		}

		public Criteria andKeywordidEqualTo(Integer value) {
			addCriterion("keywordid =", value, "keywordid");
			return (Criteria) this;
		}

		public Criteria andKeywordidNotEqualTo(Integer value) {
			addCriterion("keywordid <>", value, "keywordid");
			return (Criteria) this;
		}

		public Criteria andKeywordidGreaterThan(Integer value) {
			addCriterion("keywordid >", value, "keywordid");
			return (Criteria) this;
		}

		public Criteria andKeywordidGreaterThanOrEqualTo(Integer value) {
			addCriterion("keywordid >=", value, "keywordid");
			return (Criteria) this;
		}

		public Criteria andKeywordidLessThan(Integer value) {
			addCriterion("keywordid <", value, "keywordid");
			return (Criteria) this;
		}

		public Criteria andKeywordidLessThanOrEqualTo(Integer value) {
			addCriterion("keywordid <=", value, "keywordid");
			return (Criteria) this;
		}

		public Criteria andKeywordidIn(List<Integer> values) {
			addCriterion("keywordid in", values, "keywordid");
			return (Criteria) this;
		}

		public Criteria andKeywordidNotIn(List<Integer> values) {
			addCriterion("keywordid not in", values, "keywordid");
			return (Criteria) this;
		}

		public Criteria andKeywordidBetween(Integer value1, Integer value2) {
			addCriterion("keywordid between", value1, value2, "keywordid");
			return (Criteria) this;
		}

		public Criteria andKeywordidNotBetween(Integer value1, Integer value2) {
			addCriterion("keywordid not between", value1, value2, "keywordid");
			return (Criteria) this;
		}

		public Criteria andCrawlIdIsNull() {
			addCriterion("crawl_id is null");
			return (Criteria) this;
		}

		public Criteria andCrawlIdIsNotNull() {
			addCriterion("crawl_id is not null");
			return (Criteria) this;
		}

		public Criteria andCrawlIdEqualTo(Integer value) {
			addCriterion("crawl_id =", value, "crawlId");
			return (Criteria) this;
		}

		public Criteria andCrawlIdNotEqualTo(Integer value) {
			addCriterion("crawl_id <>", value, "crawlId");
			return (Criteria) this;
		}

		public Criteria andCrawlIdGreaterThan(Integer value) {
			addCriterion("crawl_id >", value, "crawlId");
			return (Criteria) this;
		}

		public Criteria andCrawlIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("crawl_id >=", value, "crawlId");
			return (Criteria) this;
		}

		public Criteria andCrawlIdLessThan(Integer value) {
			addCriterion("crawl_id <", value, "crawlId");
			return (Criteria) this;
		}

		public Criteria andCrawlIdLessThanOrEqualTo(Integer value) {
			addCriterion("crawl_id <=", value, "crawlId");
			return (Criteria) this;
		}

		public Criteria andCrawlIdIn(List<Integer> values) {
			addCriterion("crawl_id in", values, "crawlId");
			return (Criteria) this;
		}

		public Criteria andCrawlIdNotIn(List<Integer> values) {
			addCriterion("crawl_id not in", values, "crawlId");
			return (Criteria) this;
		}

		public Criteria andCrawlIdBetween(Integer value1, Integer value2) {
			addCriterion("crawl_id between", value1, value2, "crawlId");
			return (Criteria) this;
		}

		public Criteria andCrawlIdNotBetween(Integer value1, Integer value2) {
			addCriterion("crawl_id not between", value1, value2, "crawlId");
			return (Criteria) this;
		}

		public Criteria andKeywordIsNull() {
			addCriterion("keyword is null");
			return (Criteria) this;
		}

		public Criteria andKeywordIsNotNull() {
			addCriterion("keyword is not null");
			return (Criteria) this;
		}

		public Criteria andKeywordEqualTo(String value) {
			addCriterion("keyword =", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordNotEqualTo(String value) {
			addCriterion("keyword <>", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordGreaterThan(String value) {
			addCriterion("keyword >", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordGreaterThanOrEqualTo(String value) {
			addCriterion("keyword >=", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordLessThan(String value) {
			addCriterion("keyword <", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordLessThanOrEqualTo(String value) {
			addCriterion("keyword <=", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordLike(String value) {
			addCriterion("keyword like", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordNotLike(String value) {
			addCriterion("keyword not like", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordIn(List<String> values) {
			addCriterion("keyword in", values, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordNotIn(List<String> values) {
			addCriterion("keyword not in", values, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordBetween(String value1, String value2) {
			addCriterion("keyword between", value1, value2, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordNotBetween(String value1, String value2) {
			addCriterion("keyword not between", value1, value2, "keyword");
			return (Criteria) this;
		}

		public Criteria andCrawlTimeIsNull() {
			addCriterion("crawl_time is null");
			return (Criteria) this;
		}

		public Criteria andCrawlTimeIsNotNull() {
			addCriterion("crawl_time is not null");
			return (Criteria) this;
		}

		public Criteria andCrawlTimeEqualTo(Date value) {
			addCriterionForJDBCDate("crawl_time =", value, "crawlTime");
			return (Criteria) this;
		}

		public Criteria andCrawlTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("crawl_time <>", value, "crawlTime");
			return (Criteria) this;
		}

		public Criteria andCrawlTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("crawl_time >", value, "crawlTime");
			return (Criteria) this;
		}

		public Criteria andCrawlTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("crawl_time >=", value, "crawlTime");
			return (Criteria) this;
		}

		public Criteria andCrawlTimeLessThan(Date value) {
			addCriterionForJDBCDate("crawl_time <", value, "crawlTime");
			return (Criteria) this;
		}

		public Criteria andCrawlTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("crawl_time <=", value, "crawlTime");
			return (Criteria) this;
		}

		public Criteria andCrawlTimeIn(List<Date> values) {
			addCriterionForJDBCDate("crawl_time in", values, "crawlTime");
			return (Criteria) this;
		}

		public Criteria andCrawlTimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("crawl_time not in", values, "crawlTime");
			return (Criteria) this;
		}

		public Criteria andCrawlTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("crawl_time between", value1, value2,
					"crawlTime");
			return (Criteria) this;
		}

		public Criteria andCrawlTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("crawl_time not between", value1, value2,
					"crawlTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ptf_crawl_keyword
	 * @mbggenerated  Tue Jan 27 09:49:34 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ptf_crawl_keyword
     *
     * @mbggenerated do_not_delete_during_merge Tue Jan 27 09:48:32 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}