package com.unbank.mybatis.entity;

public class ArticleCrawlIdToDocId {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_crawlid_docid.id
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_crawlid_docid.crawl_id
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	private Integer crawlId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_crawlid_docid.doc_id
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	private Integer docId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_crawlid_docid.id
	 * @return  the value of ptf_crawlid_docid.id
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_crawlid_docid.id
	 * @param id  the value for ptf_crawlid_docid.id
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_crawlid_docid.crawl_id
	 * @return  the value of ptf_crawlid_docid.crawl_id
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	public Integer getCrawlId() {
		return crawlId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_crawlid_docid.crawl_id
	 * @param crawlId  the value for ptf_crawlid_docid.crawl_id
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	public void setCrawlId(Integer crawlId) {
		this.crawlId = crawlId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_crawlid_docid.doc_id
	 * @return  the value of ptf_crawlid_docid.doc_id
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	public Integer getDocId() {
		return docId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_crawlid_docid.doc_id
	 * @param docId  the value for ptf_crawlid_docid.doc_id
	 * @mbggenerated  Mon Mar 09 11:01:44 GMT+08:00 2015
	 */
	public void setDocId(Integer docId) {
		this.docId = docId;
	}
}