package com.unbank.mybatis.entity;

public class ArticleLocation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_crawl_location.id
     *
     * @mbggenerated Sat Feb 28 10:33:05 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_crawl_location.crawl_id
     *
     * @mbggenerated Sat Feb 28 10:33:05 CST 2015
     */
    private Integer crawlId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_crawl_location.location
     *
     * @mbggenerated Sat Feb 28 10:33:05 CST 2015
     */
    private String location;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_crawl_location.id
     *
     * @return the value of ptf_crawl_location.id
     *
     * @mbggenerated Sat Feb 28 10:33:05 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_crawl_location.id
     *
     * @param id the value for ptf_crawl_location.id
     *
     * @mbggenerated Sat Feb 28 10:33:05 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_crawl_location.crawl_id
     *
     * @return the value of ptf_crawl_location.crawl_id
     *
     * @mbggenerated Sat Feb 28 10:33:05 CST 2015
     */
    public Integer getCrawlId() {
        return crawlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_crawl_location.crawl_id
     *
     * @param crawlId the value for ptf_crawl_location.crawl_id
     *
     * @mbggenerated Sat Feb 28 10:33:05 CST 2015
     */
    public void setCrawlId(Integer crawlId) {
        this.crawlId = crawlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_crawl_location.location
     *
     * @return the value of ptf_crawl_location.location
     *
     * @mbggenerated Sat Feb 28 10:33:05 CST 2015
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_crawl_location.location
     *
     * @param location the value for ptf_crawl_location.location
     *
     * @mbggenerated Sat Feb 28 10:33:05 CST 2015
     */
    public void setLocation(String location) {
        this.location = location;
    }
}