package com.unbank.mybatis.entity;

public class ArticlePlateKeyword {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_crawl_plate_keyword.id
     *
     * @mbggenerated Wed Mar 11 14:17:45 GMT+08:00 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_crawl_plate_keyword.crawl_id
     *
     * @mbggenerated Wed Mar 11 14:17:45 GMT+08:00 2015
     */
    private Integer crawlId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_crawl_plate_keyword.keyword
     *
     * @mbggenerated Wed Mar 11 14:17:45 GMT+08:00 2015
     */
    private String keyword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_crawl_plate_keyword.plate_id
     *
     * @mbggenerated Wed Mar 11 14:17:45 GMT+08:00 2015
     */
    private Integer plateId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_crawl_plate_keyword.id
     *
     * @return the value of ptf_crawl_plate_keyword.id
     *
     * @mbggenerated Wed Mar 11 14:17:45 GMT+08:00 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_crawl_plate_keyword.id
     *
     * @param id the value for ptf_crawl_plate_keyword.id
     *
     * @mbggenerated Wed Mar 11 14:17:45 GMT+08:00 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_crawl_plate_keyword.crawl_id
     *
     * @return the value of ptf_crawl_plate_keyword.crawl_id
     *
     * @mbggenerated Wed Mar 11 14:17:45 GMT+08:00 2015
     */
    public Integer getCrawlId() {
        return crawlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_crawl_plate_keyword.crawl_id
     *
     * @param crawlId the value for ptf_crawl_plate_keyword.crawl_id
     *
     * @mbggenerated Wed Mar 11 14:17:45 GMT+08:00 2015
     */
    public void setCrawlId(Integer crawlId) {
        this.crawlId = crawlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_crawl_plate_keyword.keyword
     *
     * @return the value of ptf_crawl_plate_keyword.keyword
     *
     * @mbggenerated Wed Mar 11 14:17:45 GMT+08:00 2015
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_crawl_plate_keyword.keyword
     *
     * @param keyword the value for ptf_crawl_plate_keyword.keyword
     *
     * @mbggenerated Wed Mar 11 14:17:45 GMT+08:00 2015
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_crawl_plate_keyword.plate_id
     *
     * @return the value of ptf_crawl_plate_keyword.plate_id
     *
     * @mbggenerated Wed Mar 11 14:17:45 GMT+08:00 2015
     */
    public Integer getPlateId() {
        return plateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_crawl_plate_keyword.plate_id
     *
     * @param plateId the value for ptf_crawl_plate_keyword.plate_id
     *
     * @mbggenerated Wed Mar 11 14:17:45 GMT+08:00 2015
     */
    public void setPlateId(Integer plateId) {
        this.plateId = plateId;
    }
}