package com.unbank.mybatis.entity;

public class ArticleOrganization {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_crawl_organization.id
     *
     * @mbggenerated Sat Feb 28 10:33:05 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_crawl_organization.crawl_id
     *
     * @mbggenerated Sat Feb 28 10:33:05 CST 2015
     */
    private Integer crawlId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_crawl_organization.organization_name
     *
     * @mbggenerated Sat Feb 28 10:33:05 CST 2015
     */
    private String organizationName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_crawl_organization.id
     *
     * @return the value of ptf_crawl_organization.id
     *
     * @mbggenerated Sat Feb 28 10:33:05 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_crawl_organization.id
     *
     * @param id the value for ptf_crawl_organization.id
     *
     * @mbggenerated Sat Feb 28 10:33:05 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_crawl_organization.crawl_id
     *
     * @return the value of ptf_crawl_organization.crawl_id
     *
     * @mbggenerated Sat Feb 28 10:33:05 CST 2015
     */
    public Integer getCrawlId() {
        return crawlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_crawl_organization.crawl_id
     *
     * @param crawlId the value for ptf_crawl_organization.crawl_id
     *
     * @mbggenerated Sat Feb 28 10:33:05 CST 2015
     */
    public void setCrawlId(Integer crawlId) {
        this.crawlId = crawlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_crawl_organization.organization_name
     *
     * @return the value of ptf_crawl_organization.organization_name
     *
     * @mbggenerated Sat Feb 28 10:33:05 CST 2015
     */
    public String getOrganizationName() {
        return organizationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_crawl_organization.organization_name
     *
     * @param organizationName the value for ptf_crawl_organization.organization_name
     *
     * @mbggenerated Sat Feb 28 10:33:05 CST 2015
     */
    public void setOrganizationName(String organizationName) {
        this.organizationName = organizationName;
    }
}