package com.unbank.mybatis.entity;

public class ArticleUnbankKeyword {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_unbank_keyword.id
     *
     * @mbggenerated Tue Mar 24 14:49:22 GMT+08:00 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_unbank_keyword.keyword
     *
     * @mbggenerated Tue Mar 24 14:49:22 GMT+08:00 2015
     */
    private String keyword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_unbank_keyword.id
     *
     * @return the value of ptf_unbank_keyword.id
     *
     * @mbggenerated Tue Mar 24 14:49:22 GMT+08:00 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_unbank_keyword.id
     *
     * @param id the value for ptf_unbank_keyword.id
     *
     * @mbggenerated Tue Mar 24 14:49:22 GMT+08:00 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_unbank_keyword.keyword
     *
     * @return the value of ptf_unbank_keyword.keyword
     *
     * @mbggenerated Tue Mar 24 14:49:22 GMT+08:00 2015
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_unbank_keyword.keyword
     *
     * @param keyword the value for ptf_unbank_keyword.keyword
     *
     * @mbggenerated Tue Mar 24 14:49:22 GMT+08:00 2015
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }
}