package com.unbank.mybatis.entity;

public class ArticleCrawlIDSimilarId {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_crawlid_similarid.id
     *
     * @mbggenerated Wed Mar 11 14:49:44 GMT+08:00 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_crawlid_similarid.crawlid
     *
     * @mbggenerated Wed Mar 11 14:49:44 GMT+08:00 2015
     */
    private Integer crawlid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_crawlid_similarid.similarid
     *
     * @mbggenerated Wed Mar 11 14:49:44 GMT+08:00 2015
     */
    private Integer similarid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_crawlid_similarid.id
     *
     * @return the value of ptf_crawlid_similarid.id
     *
     * @mbggenerated Wed Mar 11 14:49:44 GMT+08:00 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_crawlid_similarid.id
     *
     * @param id the value for ptf_crawlid_similarid.id
     *
     * @mbggenerated Wed Mar 11 14:49:44 GMT+08:00 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_crawlid_similarid.crawlid
     *
     * @return the value of ptf_crawlid_similarid.crawlid
     *
     * @mbggenerated Wed Mar 11 14:49:44 GMT+08:00 2015
     */
    public Integer getCrawlid() {
        return crawlid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_crawlid_similarid.crawlid
     *
     * @param crawlid the value for ptf_crawlid_similarid.crawlid
     *
     * @mbggenerated Wed Mar 11 14:49:44 GMT+08:00 2015
     */
    public void setCrawlid(Integer crawlid) {
        this.crawlid = crawlid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_crawlid_similarid.similarid
     *
     * @return the value of ptf_crawlid_similarid.similarid
     *
     * @mbggenerated Wed Mar 11 14:49:44 GMT+08:00 2015
     */
    public Integer getSimilarid() {
        return similarid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_crawlid_similarid.similarid
     *
     * @param similarid the value for ptf_crawlid_similarid.similarid
     *
     * @mbggenerated Wed Mar 11 14:49:44 GMT+08:00 2015
     */
    public void setSimilarid(Integer similarid) {
        this.similarid = similarid;
    }
}