package com.unbank.mybatis.entity;

import java.util.Date;

public class ArticleKeyword {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_crawl_keyword.keywordid
	 * @mbggenerated  Tue Jan 27 09:49:34 CST 2015
	 */
	private Integer keywordid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_crawl_keyword.crawl_id
	 * @mbggenerated  Tue Jan 27 09:49:34 CST 2015
	 */
	private Integer crawlId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_crawl_keyword.keyword
	 * @mbggenerated  Tue Jan 27 09:49:34 CST 2015
	 */
	private String keyword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_crawl_keyword.crawl_time
	 * @mbggenerated  Tue Jan 27 09:49:34 CST 2015
	 */
	private Date crawlTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_crawl_keyword.keywordid
	 * @return  the value of ptf_crawl_keyword.keywordid
	 * @mbggenerated  Tue Jan 27 09:49:34 CST 2015
	 */
	public Integer getKeywordid() {
		return keywordid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_crawl_keyword.keywordid
	 * @param keywordid  the value for ptf_crawl_keyword.keywordid
	 * @mbggenerated  Tue Jan 27 09:49:34 CST 2015
	 */
	public void setKeywordid(Integer keywordid) {
		this.keywordid = keywordid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_crawl_keyword.crawl_id
	 * @return  the value of ptf_crawl_keyword.crawl_id
	 * @mbggenerated  Tue Jan 27 09:49:34 CST 2015
	 */
	public Integer getCrawlId() {
		return crawlId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_crawl_keyword.crawl_id
	 * @param crawlId  the value for ptf_crawl_keyword.crawl_id
	 * @mbggenerated  Tue Jan 27 09:49:34 CST 2015
	 */
	public void setCrawlId(Integer crawlId) {
		this.crawlId = crawlId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_crawl_keyword.keyword
	 * @return  the value of ptf_crawl_keyword.keyword
	 * @mbggenerated  Tue Jan 27 09:49:34 CST 2015
	 */
	public String getKeyword() {
		return keyword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_crawl_keyword.keyword
	 * @param keyword  the value for ptf_crawl_keyword.keyword
	 * @mbggenerated  Tue Jan 27 09:49:34 CST 2015
	 */
	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_crawl_keyword.crawl_time
	 * @return  the value of ptf_crawl_keyword.crawl_time
	 * @mbggenerated  Tue Jan 27 09:49:34 CST 2015
	 */
	public Date getCrawlTime() {
		return crawlTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_crawl_keyword.crawl_time
	 * @param crawlTime  the value for ptf_crawl_keyword.crawl_time
	 * @mbggenerated  Tue Jan 27 09:49:34 CST 2015
	 */
	public void setCrawlTime(Date crawlTime) {
		this.crawlTime = crawlTime;
	}
}