package com.unbank.mybatis.entity;

public class ClassWebsiteid {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_websiteid.id
     *
     * @mbggenerated Fri Mar 27 11:40:50 GMT+08:00 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_websiteid.classid
     *
     * @mbggenerated Fri Mar 27 11:40:50 GMT+08:00 2015
     */
    private Integer classid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_websiteid.websiteid
     *
     * @mbggenerated Fri Mar 27 11:40:50 GMT+08:00 2015
     */
    private Integer websiteid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_websiteid.id
     *
     * @return the value of class_websiteid.id
     *
     * @mbggenerated Fri Mar 27 11:40:50 GMT+08:00 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_websiteid.id
     *
     * @param id the value for class_websiteid.id
     *
     * @mbggenerated Fri Mar 27 11:40:50 GMT+08:00 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_websiteid.classid
     *
     * @return the value of class_websiteid.classid
     *
     * @mbggenerated Fri Mar 27 11:40:50 GMT+08:00 2015
     */
    public Integer getClassid() {
        return classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_websiteid.classid
     *
     * @param classid the value for class_websiteid.classid
     *
     * @mbggenerated Fri Mar 27 11:40:50 GMT+08:00 2015
     */
    public void setClassid(Integer classid) {
        this.classid = classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_websiteid.websiteid
     *
     * @return the value of class_websiteid.websiteid
     *
     * @mbggenerated Fri Mar 27 11:40:50 GMT+08:00 2015
     */
    public Integer getWebsiteid() {
        return websiteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_websiteid.websiteid
     *
     * @param websiteid the value for class_websiteid.websiteid
     *
     * @mbggenerated Fri Mar 27 11:40:50 GMT+08:00 2015
     */
    public void setWebsiteid(Integer websiteid) {
        this.websiteid = websiteid;
    }
}