package com.unbank.mybatis.entity;

public class ClassNoNeedKeyword {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_no_need_keyword.id
     *
     * @mbggenerated Tue May 19 15:23:55 GMT+08:00 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_no_need_keyword.classid
     *
     * @mbggenerated Tue May 19 15:23:55 GMT+08:00 2015
     */
    private Integer classid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_no_need_keyword.keyword
     *
     * @mbggenerated Tue May 19 15:23:55 GMT+08:00 2015
     */
    private String keyword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_no_need_keyword.id
     *
     * @return the value of class_no_need_keyword.id
     *
     * @mbggenerated Tue May 19 15:23:55 GMT+08:00 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_no_need_keyword.id
     *
     * @param id the value for class_no_need_keyword.id
     *
     * @mbggenerated Tue May 19 15:23:55 GMT+08:00 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_no_need_keyword.classid
     *
     * @return the value of class_no_need_keyword.classid
     *
     * @mbggenerated Tue May 19 15:23:55 GMT+08:00 2015
     */
    public Integer getClassid() {
        return classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_no_need_keyword.classid
     *
     * @param classid the value for class_no_need_keyword.classid
     *
     * @mbggenerated Tue May 19 15:23:55 GMT+08:00 2015
     */
    public void setClassid(Integer classid) {
        this.classid = classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_no_need_keyword.keyword
     *
     * @return the value of class_no_need_keyword.keyword
     *
     * @mbggenerated Tue May 19 15:23:55 GMT+08:00 2015
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_no_need_keyword.keyword
     *
     * @param keyword the value for class_no_need_keyword.keyword
     *
     * @mbggenerated Tue May 19 15:23:55 GMT+08:00 2015
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }
}