package com.unbank.mybatis.entity;

public class ClassSection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_section.id
     *
     * @mbggenerated Fri Mar 27 10:55:27 GMT+08:00 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_section.classname
     *
     * @mbggenerated Fri Mar 27 10:55:27 GMT+08:00 2015
     */
    private String classname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_section.strucutureid
     *
     * @mbggenerated Fri Mar 27 10:55:27 GMT+08:00 2015
     */
    private Integer strucutureid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_section.templateid
     *
     * @mbggenerated Fri Mar 27 10:55:27 GMT+08:00 2015
     */
    private Integer templateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_section.forumid
     *
     * @mbggenerated Fri Mar 27 10:55:27 GMT+08:00 2015
     */
    private Integer forumid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_section.status
     *
     * @mbggenerated Fri Mar 27 10:55:27 GMT+08:00 2015
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_section.id
     *
     * @return the value of class_section.id
     *
     * @mbggenerated Fri Mar 27 10:55:27 GMT+08:00 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_section.id
     *
     * @param id the value for class_section.id
     *
     * @mbggenerated Fri Mar 27 10:55:27 GMT+08:00 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_section.classname
     *
     * @return the value of class_section.classname
     *
     * @mbggenerated Fri Mar 27 10:55:27 GMT+08:00 2015
     */
    public String getClassname() {
        return classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_section.classname
     *
     * @param classname the value for class_section.classname
     *
     * @mbggenerated Fri Mar 27 10:55:27 GMT+08:00 2015
     */
    public void setClassname(String classname) {
        this.classname = classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_section.strucutureid
     *
     * @return the value of class_section.strucutureid
     *
     * @mbggenerated Fri Mar 27 10:55:27 GMT+08:00 2015
     */
    public Integer getStrucutureid() {
        return strucutureid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_section.strucutureid
     *
     * @param strucutureid the value for class_section.strucutureid
     *
     * @mbggenerated Fri Mar 27 10:55:27 GMT+08:00 2015
     */
    public void setStrucutureid(Integer strucutureid) {
        this.strucutureid = strucutureid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_section.templateid
     *
     * @return the value of class_section.templateid
     *
     * @mbggenerated Fri Mar 27 10:55:27 GMT+08:00 2015
     */
    public Integer getTemplateid() {
        return templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_section.templateid
     *
     * @param templateid the value for class_section.templateid
     *
     * @mbggenerated Fri Mar 27 10:55:27 GMT+08:00 2015
     */
    public void setTemplateid(Integer templateid) {
        this.templateid = templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_section.forumid
     *
     * @return the value of class_section.forumid
     *
     * @mbggenerated Fri Mar 27 10:55:27 GMT+08:00 2015
     */
    public Integer getForumid() {
        return forumid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_section.forumid
     *
     * @param forumid the value for class_section.forumid
     *
     * @mbggenerated Fri Mar 27 10:55:27 GMT+08:00 2015
     */
    public void setForumid(Integer forumid) {
        this.forumid = forumid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_section.status
     *
     * @return the value of class_section.status
     *
     * @mbggenerated Fri Mar 27 10:55:27 GMT+08:00 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_section.status
     *
     * @param status the value for class_section.status
     *
     * @mbggenerated Fri Mar 27 10:55:27 GMT+08:00 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}