package com.unbank.mybatis.entity;

public class CustModuleConstraint {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moduleconstraint.id
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moduleconstraint.mid
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    private Integer mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moduleconstraint.uid
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moduleconstraint.adminid
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    private Integer adminid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moduleconstraint.moduleconstraint
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    private String moduleconstraint;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moduleconstraint.id
     *
     * @return the value of moduleconstraint.id
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moduleconstraint.id
     *
     * @param id the value for moduleconstraint.id
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moduleconstraint.mid
     *
     * @return the value of moduleconstraint.mid
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moduleconstraint.mid
     *
     * @param mid the value for moduleconstraint.mid
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moduleconstraint.uid
     *
     * @return the value of moduleconstraint.uid
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moduleconstraint.uid
     *
     * @param uid the value for moduleconstraint.uid
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moduleconstraint.adminid
     *
     * @return the value of moduleconstraint.adminid
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    public Integer getAdminid() {
        return adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moduleconstraint.adminid
     *
     * @param adminid the value for moduleconstraint.adminid
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    public void setAdminid(Integer adminid) {
        this.adminid = adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moduleconstraint.moduleconstraint
     *
     * @return the value of moduleconstraint.moduleconstraint
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    public String getModuleconstraint() {
        return moduleconstraint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moduleconstraint.moduleconstraint
     *
     * @param moduleconstraint the value for moduleconstraint.moduleconstraint
     *
     * @mbggenerated Mon Jun 01 13:51:36 GMT+08:00 2015
     */
    public void setModuleconstraint(String moduleconstraint) {
        this.moduleconstraint = moduleconstraint;
    }
}