package com.unbank.mybatis.entity;

public class Sectionlabel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plate_label.id
     *
     * @mbggenerated Wed Mar 11 14:17:45 GMT+08:00 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plate_label.labelName
     *
     * @mbggenerated Wed Mar 11 14:17:45 GMT+08:00 2015
     */
    private String labelname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plate_label.id
     *
     * @return the value of plate_label.id
     *
     * @mbggenerated Wed Mar 11 14:17:45 GMT+08:00 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plate_label.id
     *
     * @param id the value for plate_label.id
     *
     * @mbggenerated Wed Mar 11 14:17:45 GMT+08:00 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plate_label.labelName
     *
     * @return the value of plate_label.labelName
     *
     * @mbggenerated Wed Mar 11 14:17:45 GMT+08:00 2015
     */
    public String getLabelname() {
        return labelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plate_label.labelName
     *
     * @param labelname the value for plate_label.labelName
     *
     * @mbggenerated Wed Mar 11 14:17:45 GMT+08:00 2015
     */
    public void setLabelname(String labelname) {
        this.labelname = labelname;
    }
}