package com.unbank.mybatis.entity;

public class UserErrorPushInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_error_push_info.id
     *
     * @mbggenerated Fri Jun 19 10:15:51 GMT+08:00 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_error_push_info.istask
     *
     * @mbggenerated Fri Jun 19 10:15:51 GMT+08:00 2015
     */
    private Integer istask;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_error_push_info.error_push_info
     *
     * @mbggenerated Fri Jun 19 10:15:51 GMT+08:00 2015
     */
    private String errorPushInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_error_push_info.id
     *
     * @return the value of user_error_push_info.id
     *
     * @mbggenerated Fri Jun 19 10:15:51 GMT+08:00 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_error_push_info.id
     *
     * @param id the value for user_error_push_info.id
     *
     * @mbggenerated Fri Jun 19 10:15:51 GMT+08:00 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_error_push_info.istask
     *
     * @return the value of user_error_push_info.istask
     *
     * @mbggenerated Fri Jun 19 10:15:51 GMT+08:00 2015
     */
    public Integer getIstask() {
        return istask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_error_push_info.istask
     *
     * @param istask the value for user_error_push_info.istask
     *
     * @mbggenerated Fri Jun 19 10:15:51 GMT+08:00 2015
     */
    public void setIstask(Integer istask) {
        this.istask = istask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_error_push_info.error_push_info
     *
     * @return the value of user_error_push_info.error_push_info
     *
     * @mbggenerated Fri Jun 19 10:15:51 GMT+08:00 2015
     */
    public String getErrorPushInfo() {
        return errorPushInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_error_push_info.error_push_info
     *
     * @param errorPushInfo the value for user_error_push_info.error_push_info
     *
     * @mbggenerated Fri Jun 19 10:15:51 GMT+08:00 2015
     */
    public void setErrorPushInfo(String errorPushInfo) {
        this.errorPushInfo = errorPushInfo;
    }
}