package com.unbank.mybatis.entity;

public class UserPushInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_push_info.id
     *
     * @mbggenerated Fri Jun 19 10:15:51 GMT+08:00 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_push_info.userid
     *
     * @mbggenerated Fri Jun 19 10:15:51 GMT+08:00 2015
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_push_info.calssname
     *
     * @mbggenerated Fri Jun 19 10:15:51 GMT+08:00 2015
     */
    private String calssname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_push_info.id
     *
     * @return the value of user_push_info.id
     *
     * @mbggenerated Fri Jun 19 10:15:51 GMT+08:00 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_push_info.id
     *
     * @param id the value for user_push_info.id
     *
     * @mbggenerated Fri Jun 19 10:15:51 GMT+08:00 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_push_info.userid
     *
     * @return the value of user_push_info.userid
     *
     * @mbggenerated Fri Jun 19 10:15:51 GMT+08:00 2015
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_push_info.userid
     *
     * @param userid the value for user_push_info.userid
     *
     * @mbggenerated Fri Jun 19 10:15:51 GMT+08:00 2015
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_push_info.calssname
     *
     * @return the value of user_push_info.calssname
     *
     * @mbggenerated Fri Jun 19 10:15:51 GMT+08:00 2015
     */
    public String getCalssname() {
        return calssname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_push_info.calssname
     *
     * @param calssname the value for user_push_info.calssname
     *
     * @mbggenerated Fri Jun 19 10:15:51 GMT+08:00 2015
     */
    public void setCalssname(String calssname) {
        this.calssname = calssname;
    }
}