
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.unbank.classify;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.3
 * Wed Aug 13 14:48:23 GMT+08:00 2014
 * Generated source version: 2.1.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "AutoclassinterfaceImplService",
                      portName = "AutoclassinterfaceImplPort",
                      targetNamespace = "http://cxfinterface.unbank.com/",
                      wsdlLocation = "http://10.0.2.25:6789/automaticsort/Autoclassinterface?wsdl",
                      endpointInterface = "com.unbank.transfer.Autoclassinterface")
                      
public class AutoclassinterfaceImpl implements Autoclassinterface {

    private static final Logger LOG = Logger.getLogger(AutoclassinterfaceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.unbank.transfer.Autoclassinterface#comparesimilarity(java.lang.String  arg0 )*
     */
    public java.lang.String comparesimilarity(java.lang.String arg0) { 
        LOG.info("Executing operation comparesimilarity");
        System.out.println(arg0);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
