package com.unbank.classify;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.3
 * Wed Aug 13 14:48:23 GMT+08:00 2014
 * Generated source version: 2.1.3
 * 
 */
 
@WebService(targetNamespace = "http://cxfinterface.unbank.com/", name = "Autoclassinterface")
public interface Autoclassinterface {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "comparesimilarity", targetNamespace = "http://cxfinterface.unbank.com/", className = "com.unbank.transfer.Comparesimilarity")
    @ResponseWrapper(localName = "comparesimilarityResponse", targetNamespace = "http://cxfinterface.unbank.com/", className = "com.unbank.transfer.ComparesimilarityResponse")
    @WebMethod
    public java.lang.String comparesimilarity(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
